version: '2'

services:
    php:
        build:
            context: php
            args:
                HOST_USER_ID: ${HOST_USER_ID}
                HOST_GROUP_ID: ${HOST_GROUP_ID}
        volumes:
            - ${APP_PATH}:/var/www:cached
